# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-14 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_calls', '0002_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='service_area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
            ],
        ),
    ]
